# Generated by Django 4.1.3 on 2023-03-15 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('published', models.DateTimeField(default=datetime.datetime(2023, 3, 15, 10, 51, 18, 639012, tzinfo=datetime.timezone.utc), verbose_name='published')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True, verbose_name='datetime_creation')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime_modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('dr', 'draft'), ('pu', 'published')], max_length=10, verbose_name='status')),
            ],
        ),
    ]
