# Generated by Django 4.1.3 on 2023-03-15 11:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 11, 1, 21, 322042, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
    ]
