# Generated by Django 4.1.7 on 2023-03-15 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_slug_alter_blogpost_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=1, upload_to='media', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 22, 24, 21, 317431, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
    ]
