# Generated by Django 4.1.7 on 2023-03-25 13:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_blogpost_image_alter_blogpost_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 13, 12, 23, 903852, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.CreateModel(
            name='BlogPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('stars', models.CharField(choices=[('1', 'worst'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'perfect')], max_length=10, verbose_name='Stars')),
                ('is_active', models.BooleanField(verbose_name='is_active')),
                ('published', models.DateTimeField(default=datetime.datetime(2023, 3, 25, 13, 12, 23, 905852, tzinfo=datetime.timezone.utc), verbose_name='published')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True, verbose_name='datetime_creation')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime_modified')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='BlogPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blog Post Comment',
                'verbose_name_plural': 'Blog Post Comments',
            },
        ),
    ]
