# Generated by Django 4.1.7 on 2023-03-26 19:50

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_options_alter_blogpost_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 19, 50, 8, 40402, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 19, 50, 8, 41438, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
    ]
