# Generated by Django 4.1.7 on 2023-03-27 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_content_alter_blogpost_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 7, 7, 25, 859271, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 7, 7, 25, 861301, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
    ]
