# Generated by Django 4.1.7 on 2023-04-01 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('position', models.IntegerField(verbose_name='position')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 10, 11, 48, 597135, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 10, 11, 48, 599170, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(to='blog.category', verbose_name='Category'),
        ),
    ]
